name: dchisel
description: A simple dart web framework for create REST API
version: 1.0.2+3
repository: https://github.com/alalawy/DChisel

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  path: ^1.8.0
  shelf: ^1.2.0
  shelf_router: ^1.0.0
  postgres: ^2.4.1+2
  shelf_plus: ^0.0.2
  mysql1: ^0.19.2
  process_run: ^0.12.2+1

executables:
  dchisel: dchisel

#dev_dependencies:
  #pedantic: ^1.10.0
